#!/bin/sh

rm -f ~/.vimrc
ln -s $PWD/.vimrc ~/.vimrc

mkdir -p ~/.config/fish/functions
rm -f ~/.config/fish/functions/fish_user_key_bindings.fish
ln -s $PWD/.config/fish/functions/fish_user_key_bindings.fish ~/.config/fish/functions/fish_user_key_bindings.fish
rm -f ~/.config/fish/config.fish
ln -s $PWD/.config/fish/config.fish ~/.config/fish/config.fish

mkdir -p ~/.config/terminator
rm -f ~/.config/terminator/config
ln -s $PWD/.config/terminator/config ~/.config/terminator/config

rm -f ~/.conkyrc
ln -s $PWD/.conkyrc ~/.conkyrc

rm -rf ~/.vim
ln -s $PWD/.vim ~/.vim

rm -rf ~/.fluxbox
ln -s $PWD/.fluxbox ~/.fluxbox

