#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/rc/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

#(sleep 2 ; feh --bg-fill ~/wallpaper/wallpaper.png) &

#(sleep 2 ; xbattbar -t 4 &) &

(sleep 2 ; conky &) &

(sleep 2 ; volumeicon &) &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/rc/.fluxbox/log"
